<?php
    function statepoll_menu() {
        $items = array();
        $items['hello_friend'] = array(
            'title' => 'Favorite Ice Cream',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('statepoll_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );

        $items['success'] = array(
            'title' => 'Success',
            'page callback' => 'statepoll_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

function statepoll_form() {
    $form['ice_cream'] = array(
        '#title' => 'Ice Cream',
        '#type' => 'textfield',
        '#description' => t('Please enter your favorite ice cream flavor'),
        '#element_validate' => array('element_validate_these_text_fields'),
        '#required'=> TRUE,
    );

    return $form;
}

function element_validate_these_text_fields($element)
{
    // $fave_ice_cream = $element['#value'];
    $exceptions = array(0,1,2,3,4,5,6,7,8,9,"#","!","@","%");
    $exploded_words = explode(" ", $element['#value']);
        foreach ($exploded_words as $word)
        {
            foreach($word as $character)
             {
                if (in_array($element['#value'], $exceptions))
                {
                    form_error($element, t('Please enter a word only, no numbers or special characters'));
                }
             }
         }
   // return $fave_ice_cream;
}
